import ArgumentParser

struct IOSCommand: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "ios",
        abstract: "iOS release operations",
        subcommands: [
            IOSBuildCommand.self,
            IOSUploadCommand.self,
            IOSSubmitCommand.self,
            IOSMetadataCommand.self,
            IOSScreenshotsCommand.self,
            IOSBetaCommand.self,
            IOSEventsCommand.self,
            IOSPreviewsCommand.self,
            IOSPricingCommand.self,
            IOSProductPagesCommand.self,
            IOSProvisioningCommand.self,
            IOSVersionsCommand.self,
            IOSBuildsCommand.self,
            IOSSandboxTestersCommand.self,
            IOSAgeRatingCommand.self,
            IOSCategoriesCommand.self,
            IOSClipsCommand.self,
            IOSSubscriptionGroupsCommand.self,
            IOSPromoCodesCommand.self,
            IOSAnalyticsCommand.self,
            IOSFinanceCommand.self,
            IOSWebhooksCommand.self,
            IOSPhasedReleaseCommand.self,
            IOSReviewsCommand.self,
            IOSScheduleCommand.self,
            IOSReviewStatusCommand.self,
            IOSTeamCommand.self,
            IOSGameCenterCommand.self,
            IOSPreOrderCommand.self,
            IOSEULACommand.self,
            IOSAPIKeysCommand.self,
            IOSPricePointsCommand.self,
            IOSAvailabilityCommand.self,
            IOSAppInfoCommand.self,
            IOSBetaFeedbackCommand.self,
            IOSXcodeCloudCommand.self,
            IOSIAPCommand.self,
            IOSTerritoriesCommand.self,
            IOSBetaLicenseCommand.self,
            IOSExperimentsCommand.self,
            IOSSCMCommand.self,
            IOSEncryptionCommand.self,
            IOSReviewAttachmentsCommand.self,
            IOSAlternativeDistributionCommand.self,
            IOSBetaAppLocalizationsCommand.self,
            IOSWinBackOffersCommand.self,
            IOSRoutingCoverageCommand.self,
            IOSLocalizationsCommand.self,
            IOSPromotionalOffersCommand.self,
            IOSSubscriptionImagesCommand.self,
            IOSSubscriptionLocalizationsCommand.self,
            IOSIntroductoryOffersCommand.self,
            IOSCustomPageLocalizationsCommand.self,
            IOSIAPLocalizationsCommand.self,
            IOSScreenshotSetsCommand.self,
            IOSPreviewSetsCommand.self,
            IOSSubscriptionGroupLocalizationsCommand.self,
            IOSBuildBetaDetailCommand.self,
            IOSAppScreenshotsCommand.self,
            IOSIAPPriceScheduleCommand.self,
            IOSEventLocalizationsCommand.self,
            IOSSubscriptionAvailabilityCommand.self,
            IOSSubscriptionPricesCommand.self,
            IOSReviewDetailCommand.self,
        ]
    )
}
